name: chat_ai
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:  
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.2+1
  oktoast:
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - .env
  
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        
    
  
 
